/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal.documents'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedDashboardAiIndexRouteImport } from './routes/_authenticated/dashboard.ai.index'
import { Route as AuthenticatedPortalProjectsProjectIdRouteImport } from './routes/_authenticated/portal.projects.$projectId'
import { Route as AuthenticatedDashboardAiWorkflowsRouteImport } from './routes/_authenticated/dashboard.ai.workflows'
import { Route as AuthenticatedDashboardAiVoiceRouteImport } from './routes/_authenticated/dashboard.ai.voice'
import { Route as AuthenticatedDashboardAiUsageRouteImport } from './routes/_authenticated/dashboard.ai.usage'
import { Route as AuthenticatedDashboardAiPromptsRouteImport } from './routes/_authenticated/dashboard.ai.prompts'
import { Route as AuthenticatedDashboardAiKnowledgeRouteImport } from './routes/_authenticated/dashboard.ai.knowledge'
import { Route as AuthenticatedDashboardAiChatbotsRouteImport } from './routes/_authenticated/dashboard.ai.chatbots'
import { Route as AuthenticatedDashboardAiAssistantsRouteImport } from './routes/_authenticated/dashboard.ai.assistants'
import { Route as AuthenticatedDashboardAiActivityRouteImport } from './routes/_authenticated/dashboard.ai.activity'
import { Route as AuthenticatedAdminLeadLeadIdRouteImport } from './routes/_authenticated/admin.lead.$leadId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/portal/documents',
    path: '/portal/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardAiIndexRoute =
  AuthenticatedDashboardAiIndexRouteImport.update({
    id: '/dashboard/ai/',
    path: '/dashboard/ai/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalProjectsProjectIdRoute =
  AuthenticatedPortalProjectsProjectIdRouteImport.update({
    id: '/portal/projects/$projectId',
    path: '/portal/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiWorkflowsRoute =
  AuthenticatedDashboardAiWorkflowsRouteImport.update({
    id: '/dashboard/ai/workflows',
    path: '/dashboard/ai/workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiVoiceRoute =
  AuthenticatedDashboardAiVoiceRouteImport.update({
    id: '/dashboard/ai/voice',
    path: '/dashboard/ai/voice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiUsageRoute =
  AuthenticatedDashboardAiUsageRouteImport.update({
    id: '/dashboard/ai/usage',
    path: '/dashboard/ai/usage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiPromptsRoute =
  AuthenticatedDashboardAiPromptsRouteImport.update({
    id: '/dashboard/ai/prompts',
    path: '/dashboard/ai/prompts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiKnowledgeRoute =
  AuthenticatedDashboardAiKnowledgeRouteImport.update({
    id: '/dashboard/ai/knowledge',
    path: '/dashboard/ai/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiChatbotsRoute =
  AuthenticatedDashboardAiChatbotsRouteImport.update({
    id: '/dashboard/ai/chatbots',
    path: '/dashboard/ai/chatbots',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiAssistantsRoute =
  AuthenticatedDashboardAiAssistantsRouteImport.update({
    id: '/dashboard/ai/assistants',
    path: '/dashboard/ai/assistants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAiActivityRoute =
  AuthenticatedDashboardAiActivityRouteImport.update({
    id: '/dashboard/ai/activity',
    path: '/dashboard/ai/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadLeadIdRoute =
  AuthenticatedAdminLeadLeadIdRouteImport.update({
    id: '/admin/lead/$leadId',
    path: '/admin/lead/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/lead/$leadId': typeof AuthenticatedAdminLeadLeadIdRoute
  '/dashboard/ai/activity': typeof AuthenticatedDashboardAiActivityRoute
  '/dashboard/ai/assistants': typeof AuthenticatedDashboardAiAssistantsRoute
  '/dashboard/ai/chatbots': typeof AuthenticatedDashboardAiChatbotsRoute
  '/dashboard/ai/knowledge': typeof AuthenticatedDashboardAiKnowledgeRoute
  '/dashboard/ai/prompts': typeof AuthenticatedDashboardAiPromptsRoute
  '/dashboard/ai/usage': typeof AuthenticatedDashboardAiUsageRoute
  '/dashboard/ai/voice': typeof AuthenticatedDashboardAiVoiceRoute
  '/dashboard/ai/workflows': typeof AuthenticatedDashboardAiWorkflowsRoute
  '/portal/projects/$projectId': typeof AuthenticatedPortalProjectsProjectIdRoute
  '/dashboard/ai/': typeof AuthenticatedDashboardAiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/lead/$leadId': typeof AuthenticatedAdminLeadLeadIdRoute
  '/dashboard/ai/activity': typeof AuthenticatedDashboardAiActivityRoute
  '/dashboard/ai/assistants': typeof AuthenticatedDashboardAiAssistantsRoute
  '/dashboard/ai/chatbots': typeof AuthenticatedDashboardAiChatbotsRoute
  '/dashboard/ai/knowledge': typeof AuthenticatedDashboardAiKnowledgeRoute
  '/dashboard/ai/prompts': typeof AuthenticatedDashboardAiPromptsRoute
  '/dashboard/ai/usage': typeof AuthenticatedDashboardAiUsageRoute
  '/dashboard/ai/voice': typeof AuthenticatedDashboardAiVoiceRoute
  '/dashboard/ai/workflows': typeof AuthenticatedDashboardAiWorkflowsRoute
  '/portal/projects/$projectId': typeof AuthenticatedPortalProjectsProjectIdRoute
  '/dashboard/ai': typeof AuthenticatedDashboardAiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/lead/$leadId': typeof AuthenticatedAdminLeadLeadIdRoute
  '/_authenticated/dashboard/ai/activity': typeof AuthenticatedDashboardAiActivityRoute
  '/_authenticated/dashboard/ai/assistants': typeof AuthenticatedDashboardAiAssistantsRoute
  '/_authenticated/dashboard/ai/chatbots': typeof AuthenticatedDashboardAiChatbotsRoute
  '/_authenticated/dashboard/ai/knowledge': typeof AuthenticatedDashboardAiKnowledgeRoute
  '/_authenticated/dashboard/ai/prompts': typeof AuthenticatedDashboardAiPromptsRoute
  '/_authenticated/dashboard/ai/usage': typeof AuthenticatedDashboardAiUsageRoute
  '/_authenticated/dashboard/ai/voice': typeof AuthenticatedDashboardAiVoiceRoute
  '/_authenticated/dashboard/ai/workflows': typeof AuthenticatedDashboardAiWorkflowsRoute
  '/_authenticated/portal/projects/$projectId': typeof AuthenticatedPortalProjectsProjectIdRoute
  '/_authenticated/dashboard/ai/': typeof AuthenticatedDashboardAiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/admin/crm'
    | '/admin/leads'
    | '/portal/documents'
    | '/portal/'
    | '/admin/lead/$leadId'
    | '/dashboard/ai/activity'
    | '/dashboard/ai/assistants'
    | '/dashboard/ai/chatbots'
    | '/dashboard/ai/knowledge'
    | '/dashboard/ai/prompts'
    | '/dashboard/ai/usage'
    | '/dashboard/ai/voice'
    | '/dashboard/ai/workflows'
    | '/portal/projects/$projectId'
    | '/dashboard/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/admin/crm'
    | '/admin/leads'
    | '/portal/documents'
    | '/portal'
    | '/admin/lead/$leadId'
    | '/dashboard/ai/activity'
    | '/dashboard/ai/assistants'
    | '/dashboard/ai/chatbots'
    | '/dashboard/ai/knowledge'
    | '/dashboard/ai/prompts'
    | '/dashboard/ai/usage'
    | '/dashboard/ai/voice'
    | '/dashboard/ai/workflows'
    | '/portal/projects/$projectId'
    | '/dashboard/ai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/leads'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/lead/$leadId'
    | '/_authenticated/dashboard/ai/activity'
    | '/_authenticated/dashboard/ai/assistants'
    | '/_authenticated/dashboard/ai/chatbots'
    | '/_authenticated/dashboard/ai/knowledge'
    | '/_authenticated/dashboard/ai/prompts'
    | '/_authenticated/dashboard/ai/usage'
    | '/_authenticated/dashboard/ai/voice'
    | '/_authenticated/dashboard/ai/workflows'
    | '/_authenticated/portal/projects/$projectId'
    | '/_authenticated/dashboard/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/': {
      id: '/_authenticated/dashboard/ai/'
      path: '/dashboard/ai'
      fullPath: '/dashboard/ai/'
      preLoaderRoute: typeof AuthenticatedDashboardAiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/projects/$projectId': {
      id: '/_authenticated/portal/projects/$projectId'
      path: '/portal/projects/$projectId'
      fullPath: '/portal/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedPortalProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/workflows': {
      id: '/_authenticated/dashboard/ai/workflows'
      path: '/dashboard/ai/workflows'
      fullPath: '/dashboard/ai/workflows'
      preLoaderRoute: typeof AuthenticatedDashboardAiWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/voice': {
      id: '/_authenticated/dashboard/ai/voice'
      path: '/dashboard/ai/voice'
      fullPath: '/dashboard/ai/voice'
      preLoaderRoute: typeof AuthenticatedDashboardAiVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/usage': {
      id: '/_authenticated/dashboard/ai/usage'
      path: '/dashboard/ai/usage'
      fullPath: '/dashboard/ai/usage'
      preLoaderRoute: typeof AuthenticatedDashboardAiUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/prompts': {
      id: '/_authenticated/dashboard/ai/prompts'
      path: '/dashboard/ai/prompts'
      fullPath: '/dashboard/ai/prompts'
      preLoaderRoute: typeof AuthenticatedDashboardAiPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/knowledge': {
      id: '/_authenticated/dashboard/ai/knowledge'
      path: '/dashboard/ai/knowledge'
      fullPath: '/dashboard/ai/knowledge'
      preLoaderRoute: typeof AuthenticatedDashboardAiKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/chatbots': {
      id: '/_authenticated/dashboard/ai/chatbots'
      path: '/dashboard/ai/chatbots'
      fullPath: '/dashboard/ai/chatbots'
      preLoaderRoute: typeof AuthenticatedDashboardAiChatbotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/assistants': {
      id: '/_authenticated/dashboard/ai/assistants'
      path: '/dashboard/ai/assistants'
      fullPath: '/dashboard/ai/assistants'
      preLoaderRoute: typeof AuthenticatedDashboardAiAssistantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/ai/activity': {
      id: '/_authenticated/dashboard/ai/activity'
      path: '/dashboard/ai/activity'
      fullPath: '/dashboard/ai/activity'
      preLoaderRoute: typeof AuthenticatedDashboardAiActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lead/$leadId': {
      id: '/_authenticated/admin/lead/$leadId'
      path: '/admin/lead/$leadId'
      fullPath: '/admin/lead/$leadId'
      preLoaderRoute: typeof AuthenticatedAdminLeadLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedAdminLeadLeadIdRoute: typeof AuthenticatedAdminLeadLeadIdRoute
  AuthenticatedDashboardAiActivityRoute: typeof AuthenticatedDashboardAiActivityRoute
  AuthenticatedDashboardAiAssistantsRoute: typeof AuthenticatedDashboardAiAssistantsRoute
  AuthenticatedDashboardAiChatbotsRoute: typeof AuthenticatedDashboardAiChatbotsRoute
  AuthenticatedDashboardAiKnowledgeRoute: typeof AuthenticatedDashboardAiKnowledgeRoute
  AuthenticatedDashboardAiPromptsRoute: typeof AuthenticatedDashboardAiPromptsRoute
  AuthenticatedDashboardAiUsageRoute: typeof AuthenticatedDashboardAiUsageRoute
  AuthenticatedDashboardAiVoiceRoute: typeof AuthenticatedDashboardAiVoiceRoute
  AuthenticatedDashboardAiWorkflowsRoute: typeof AuthenticatedDashboardAiWorkflowsRoute
  AuthenticatedPortalProjectsProjectIdRoute: typeof AuthenticatedPortalProjectsProjectIdRoute
  AuthenticatedDashboardAiIndexRoute: typeof AuthenticatedDashboardAiIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedAdminLeadLeadIdRoute: AuthenticatedAdminLeadLeadIdRoute,
  AuthenticatedDashboardAiActivityRoute: AuthenticatedDashboardAiActivityRoute,
  AuthenticatedDashboardAiAssistantsRoute:
    AuthenticatedDashboardAiAssistantsRoute,
  AuthenticatedDashboardAiChatbotsRoute: AuthenticatedDashboardAiChatbotsRoute,
  AuthenticatedDashboardAiKnowledgeRoute:
    AuthenticatedDashboardAiKnowledgeRoute,
  AuthenticatedDashboardAiPromptsRoute: AuthenticatedDashboardAiPromptsRoute,
  AuthenticatedDashboardAiUsageRoute: AuthenticatedDashboardAiUsageRoute,
  AuthenticatedDashboardAiVoiceRoute: AuthenticatedDashboardAiVoiceRoute,
  AuthenticatedDashboardAiWorkflowsRoute:
    AuthenticatedDashboardAiWorkflowsRoute,
  AuthenticatedPortalProjectsProjectIdRoute:
    AuthenticatedPortalProjectsProjectIdRoute,
  AuthenticatedDashboardAiIndexRoute: AuthenticatedDashboardAiIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
